# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecaa65cb13b89cb6e5bac954a63d832944b176907e25ef271319ecd33f000b9087e873dc3948eb1c8c6e8801aa359803f52171a8258cf57d16c104956ef4aa1a

test:
  secret_key_base: e157796cf154bb859871a583f6eb74eb9e1822aa1bca49154aa84f14efbf335fc985e18d047d9acc7ec2ec6d497e5f73addac2be1082493f412880b7eb00c90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
